### ISSUE TITLE
创建binding插入MySQL时platform为NULL报错

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [koishijs/koishi-plugin-adapter-repl#1]
环境:
```
System:
OS: Linux 5.15 Armbian 23.08.0-trunk jammy 22.04 (Jammy Jellyfish)
CPU: (4) arm64 ARMv8 Processor rev 4 (v8l)
Binaries:
Node: 18.17.1
Yarn: 1.22.19
Koishi:
Core: 4.14.1
Console: 5.13.1
```
```
armbian:data:# mysql --version
mysql  Ver 8.0.33-0ubuntu0.22.04.4 for Linux on aarch64 ((Ubuntu))
```
尝试在运行`yarn start`的tmux中回车，显示了`>`的提示符，但立马报错:
```
2023-08-15 21:56:44 [W] mysql INSERT INTO `binding` (`aid`, `bid`, `pid`, `platform`) VALUES (18, 18, 'repl', NULL)           
2023-08-15 21:56:44 [W] session                                   
ER_BAD_NULL_ERROR: Column 'platform' cannot be null                                    
 at _MySQLDriver.query (/root/koishi/koishi-308/node_modules/@minatojs/driver-mysql/lib/index.js:311:19)                                                                
 at _MySQLDriver.create (/root/koishi/koishi-308/node_modules/@minatojs/driver-mysql/lib/index.js:444:31)
...
```
是否可以修改为 `repl` 或其他？我也可尝试直接修`libs/` ?

**Comment by zhangjing-GitHub-Code** [comment]
SUS，源码没有设置binding，所以是koishi其他地方的问题？

**Comment by shigma** [comment]
是这个插件的问题。

**Comment by zhangjing-GitHub-Code** [comment]
您好捏，改一下谢谢:)

**Comment by shigma** [comment]
会改的

**Comment by shigma** [comment]
已经更新，你看看最新版本能不能用。
